# ==============================================================================
# ==============================================================================
# Machine (machine-wide + QEMU target options)
# ==============================================================================
[Machine]
platform = "STM32F429"

qemu_path = "qemu-system-arm"

monitor_port = 5555
qmp_socket   = "/tmp/qmp.sock"

enable_gdb    = false
stop_on_start = false
launch_gdb    = false

semihosting        = true
semihosting_config = "enable=on,target=native"

coverage = true
bbl_coverage = true
finline  = ""

# ==============================================================================
# Memory
# ==============================================================================
[Memory]

  # ---------------------------------------------------------------------------
  # Main memory (required)
  #
  # Used by:  -machine <...>,memory-backend=<id>
  # Also maps: ram_baseaddr0 / ram_backend0
  # ---------------------------------------------------------------------------
  [Memory.main]
  id           = "ram0"
  base_address = "0x20000000"
  memory_size  = "512M"
  memory_type  = "SRAM"

  backend     = "file"                 # file | ram | memfd
  memory_file = "/dev/shm/my_m4_ram3"  # only when backend="file"

  share    = true
  prealloc = false


  # ---------------------------------------------------------------------------
  # Extra memory banks (optional)
  #
  # Each bank becomes:
  #   -object memory-backend-*
  #   -global <machine>-soc.ram_baseaddrN=<base_address>
  #   -global <machine>-soc.ram_backendN=<id>
  # ---------------------------------------------------------------------------
  [[Memory.ram1]]
  id           = "ram1"
  index        = 1
  base_address = "0x30000000"
  memory_size  = "512K"
  memory_type  = "SRAM"

  backend     = "file"
  memory_file = "/dev/shm/my_m4_ram"

  share    = true
  prealloc = false

# ==============================================================================
# CPUs
# ==============================================================================
[CPU]

  # ---------------------------------------------------------------------------
  # CPU 0
  # ---------------------------------------------------------------------------
  [[CPU.cpu0]]
  arch    = "arm"
  machine = "cortexm"
  cpu     = "cortex-m4"

  binary     = "boardrunner/boardrunner_examples/examples/STM32F769i-eval/GPIO_INT/firmware/STM32F769I_EVAL.elf"
  init_nsvtor = "0x08000000"

  map_file        = "courbet/rover_v422_map.txt"
  plugin_library  = "build/libfastdyn.so"
  monitor_elf     = "../ws/monitor.elf"

  log_file    = "qemu.log"
  log_options = "in_asm,op"

  twintrace = "None" #options are record, replay or None
  hardware_trace = 'hardware_log/io.log'   #useful in cases like replay to generate the replay binary

  logger_content = """
  # --- Plugin Logger Configuration ---
  # level  = DEBUG
  # output = stderr
  """


# ==============================================================================
#                              Device Configuration
# ==============================================================================

# --- Model-Specific Configurations ---
# Define the global arguments for each type of plugin device model here.

[Device.Models.elder]
    # The libhw backend is a global argument for the elder model.

[Device.Models.passthrough]
    backend = "stlink"

[Device.Models.classic]
    # The classic model has no global arguments.

[Device.Models.unhandled]
    # This model explicitly marks memory as unhandled.


# --- Peripheral Definitions ---
# Each peripheral gets its own sub-table. If it uses the elder model,
# its specific scroll configuration is defined directly within it.
[Device.gpioc]
    # STM32F7 GPIOC Range (Base: 0x40020800, Size: 0x400)
    # Handles PC13 (Tamper Button)
    ranges = [["0x40020800", "0x40020BFF"]]
    irq = [['1','100']]
    description = "GPIO Port C (AHB1) used for Tamper Button."
    read_priority = "elder"

    [[Device.gpioc.handlers]]
        model   = "elder"
        enabled = true
        scroll = "boardrunner/boardrunner_sdk/build/model.so"

    [[Device.gpioc.handlers]]
        model   = "classic"
        enabled = false

    [[Device.gpioc.handlers]]
        model   = "passthrough"
        enabled = false

    [[Device.gpioc.handlers]]
        model   = "twintrace"
        enabled = false

[Device.remaining_space]
    # Calculated to exclude GPIOC (0x40020800 - 0x40020BFF)
    # Range 1: 0x40000000 -> 0x400207FF (Before GPIOC)
    # Range 2: 0x40020C00 -> 0xEFFFFFFF (After GPIOC)
    ranges = [["0x40000000", "0x400207FF"], ["0x40020C00", "0xE0000000"], ["0xE0000000", "0xEFFFFFFF"]]
    irq = [['1','100']]
    description ='"Handles all other memory regions not covered by specific peripherals."'
    [[Device.remaining_space.handlers]]
        model = "classic"
        enabled = false

    [[Device.remaining_space.handlers]]
        model = "passthrough"
        enabled = true

    [[Device.remaining_space.handlers]]
        model = "twintrace"
        enabled = false