#QEMU DIR PATHS
option('qemu_path', type: 'string', value: '../../qemu', description: 'Path to the QEMU')
#LIBHW DIR PATHS
option('libhw_path', type: 'string', value: '../../../libhw', description: 'Path to LIBHW')
#AFLNET DIR PATHS
option('aflnet_path', type: 'string', value: '../aflnet', description: 'Path to AFLNET')

#USER Libraries
option('enable_libhw', type: 'boolean', value: false, description: 'Enable libhw support')
option('enable_libfuzz', type: 'boolean', value: false, description: 'Enable rust fuzzing support')
option('enable_aflnet', type: 'boolean', value: false, description: 'Enable protocol fuzzing support')

#Configuration Options
option('device_models', type: 'boolean', value: false, description: 'Enable device models support')
option('enable_libpy', type: 'boolean', value: false, description: 'Enable Python Library')

#debugging options
option('DEBUG_PRINT', type: 'boolean', value: false, description: 'Enable Debugging prints')


#physics support
option('enable_phy', type: 'boolean', value: false, description: 'Enable Physics Engine')
option('enable_sundials', type: 'boolean', value: false, description: 'Enable SUNDIALS solver support')
option('enable_fmu', type: 'boolean', value: false, description: 'Enable FMU engine')
option('enable_flight_controllers', type: 'boolean', value: false, description: 'Enable Flight controllers engine')
option('enable_libgz', type: 'boolean', value: false, description: 'Enable gazebo lib support')
