#QEMU DIR PATHS
option('qemu_path', type: 'string', value: '../../qemu', description: 'Path to the QEMU')
#LIBHW DIR PATHS
option('libhw_path', type: 'string', value: '../../../libhw', description: 'Path to LIBHW')

#USER Libraries
option('enable_libhw', type: 'boolean', value: false, description: 'Enable libhw support')
option('enable_libgz', type: 'boolean', value: false, description: 'Enable gazebo lib support')

#Configuration Options
option('device_models', type: 'boolean', value: false, description: 'Enable device models support')
option('enable_libpy', type: 'boolean', value: false, description: 'Enable Python Library')

#debugging options
option('DEBUG_PRINT', type: 'boolean', value: false, description: 'Enable Debugging prints')