[package]
name = "baby_fuzzer"
version = "0.14.1"
authors = [
  "Andrea Fioraldi <andreafioraldi@gmail.com>",
  "Dominik Maier <domenukk@gmail.com>",
]
edition = "2021"

[features]
default = ["std"]
tui = []
std = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = 3
debug = true

[dependencies]
banquo = "0.1.0"
banquo-parser = { path = "/home/michael-rooney/banquo/banquo-parser" }
csv = "1.4.0"
env_logger = "0.11.7"
gz-msgs = "0.9.0"
gz-transport = "0.9.0"

# libafl = { path = "../../../crates/libafl", features = ["tui_monitor"] }
# libafl_bolts = { path = "../../../crates/libafl_bolts" }
libafl = { path = "/home/michael-rooney/LibAFL-0.15.4/crates/libafl", features = ["tui_monitor"] }
libafl_bolts = { path = "/home/michael-rooney/LibAFL-0.15.4/crates/libafl_bolts" }

log = { version = "0.4.22", features = ["release_max_level_info"] }
ordered-float = "5.1.0"
protobuf = "3.7.2"
scirs2-core = "0.1.1"
scirs2-optimize = "0.1.1"
serde = "1.0.228"
serde_json = "1.0.149"
reqwest = { version = "0.11", features = ["json", "blocking"] }