# ==============================================================================
# Machine (machine-wide + QEMU target options)
# ==============================================================================
[Machine]
platform = "STM32F429"

qemu_path = "qemu-system-arm"

monitor_port = 5555
qmp_socket   = "/tmp/qmp.sock"

enable_gdb    = false
stop_on_start = false
launch_gdb    = false

semihosting        = true
semihosting_config = "enable=on,target=native"

coverage = true
bbl_coverage = true
finline  = ""

# ==============================================================================
# Memory
# ==============================================================================
[Memory]

  # ---------------------------------------------------------------------------
  # Main memory (required)
  #
  # Used by:  -machine <...>,memory-backend=<id>
  # Also maps: ram_baseaddr0 / ram_backend0
  # ---------------------------------------------------------------------------
  [Memory.main]
  id           = "ram0"
  base_address = "0x20000000"
  memory_size  = "512M"
  memory_type  = "SRAM"

  backend     = "file"                 # file | ram | memfd
  memory_file = "/dev/shm/my_m4_ram3"  # only when backend="file"

  share    = true
  prealloc = false


  # ---------------------------------------------------------------------------
  # Extra memory banks (optional)
  #
  # Each bank becomes:
  #   -object memory-backend-*
  #   -global <machine>-soc.ram_baseaddrN=<base_address>
  #   -global <machine>-soc.ram_backendN=<id>
  # ---------------------------------------------------------------------------
  [[Memory.ram1]]
  id           = "ram1"
  index        = 1
  base_address = "0x30000000"
  memory_size  = "512K"
  memory_type  = "SRAM"

  backend     = "file"
  memory_file = "/dev/shm/my_m4_ram"

  share    = true
  prealloc = false

# ==============================================================================
# CPUs
# ==============================================================================
[CPU]

  # ---------------------------------------------------------------------------
  # CPU 0
  # ---------------------------------------------------------------------------
  [[CPU.cpu0]]
  arch    = "arm"
  machine = "cortexm"
  cpu     = "cortex-m4"

  binary     = "boardrunner/boardrunner_examples/examples/STM32F769i-eval/I2C/Firmwares/I2C_TwoBoards_Master.elf"
  init_nsvtor = "0x08000000"

  map_file        = "courbet/rover_v422_map.txt"
  plugin_library  = "build/libfastdyn.so"
  monitor_elf     = "../ws/monitor.elf"

  log_file    = "qemu.log"
  log_options = "in_asm,op"

  twintrace = "None" #options are record, replay or None
  hardware_trace = 'hardware_log/io.log'   #useful in cases like replay to generate the replay binary

  logger_content = """
  # --- Plugin Logger Configuration ---
  # level  = DEBUG
  # output = stderr
  """

# Some virtuals being experimented with, not polished fuzzing

    # [[CPU.cpu0.virtuals]]
    # at          = "0x08001C80"
    # instruction = "anchor"
    # args        = ["0x40005424"]

    # [[CPU.cpu0.modifiers]] #skip pin reading
    # at          = "0x0800059C"
    # patch       = "r15 0x800059E"

    # [[CPU.cpu0.modifiers]]
    # at          = "0x08000608"
    # patch       = "r15 0x0800056A"


# ==============================================================================
# Device model defaults (global settings per model type)
# ==============================================================================
[Device.Models]

  [Device.Models.elder]
  # (empty by default)

  [Device.Models.passthrough]
  backend = "stlink"

  [Device.Models.classic]
  # (empty by default)

  [Device.Models.twintrace]
  backend = "stlink"
    # The classic model has no global arguments.

  [Device.Models.unhandled]
  # (empty by default)


# --- Peripheral Definitions ---
# Each peripheral gets its own sub-table. If it uses the elder model,
# its specific scroll configuration is defined directly within it.

[Device.i2c1]
    irq = [[0, 15], [20, 25], 41, 53]                #means the irq from 0 to 15 and irq from 20 to 25 and 41 are handled
    ranges = [["0x40005400", "0x400057FF"]]
    description = "Main USART peripheral for serial communication."
    # The configuration for this specific device when handled by the elder model.
    # 'internal_model' is the name of the model compiled into the main plugin library.
    scroll_config = """
[i2c1]
internal_model = "i2c1_model"
"""
    [[Device.i2c1.handlers]]
        model   = "elder"
        enabled = true
        scroll = "boardrunner/boardrunner_sdk/build/I2C_master_model.so"

    [[Device.i2c1.handlers]]
        model   = "passthrough"
        enabled = false # This handler is defined but will be skipped for this device.

[Device.unhandled_space]
    irq = [[0, 15], [20, 25], 41, 53]                #means the irq from 0 to 15 and irq from 20 to 25 and 41 are handled
    ranges = [["0x40000000", "0x400053FF"], ["0x40005800", "0xE00FFFFF"], ["0xE0000000", "0xEFFFFFFF"]]
    description = "Memory regions that are explicitly not handled by any model."

    [[Device.unhandled_space.handlers]]
        model = "passthrough"
        enabled = true

    [[Device.i2c1.slaves]]
        model = ["elder"]       #attach this device to elder model only
        device = "STM32F4"
        address = "0x30F"
        device_scroll = "boardrunner/boardrunner_sdk/build/I2C_slave_model.so"


# [Device.unhandled_space]
#     irq = "0-20:21-25:41:53:69"                #means the irq from 0 to 15 and irq from 20 to 25 and 41 are handled
#     ranges = ["0x00000000-0x000000FF", "0xE0000000-0xEFFFFFFF", "0x40000000-0xE00FFFFF"]
#     description = "Memory regions that are explicitly not handled by any model."

#     [[Device.unhandled_space.handlers]]
#         model = "passthrough"
#         enabled = true