# ==============================================================================
#                               Rehosting Configuration
# ==============================================================================
[Rehosting]
[Rehosting.directories]
static_analysis_cache_dir = "./fastdyn_static_analysis"
firmware_source_roots = ["/scratch/Fastdyn/ardurover_rehosting_fastdyn/source_code_ardupilot/ardupilot"]
modeling_dir = "/scratch/Fastdyn/ardurover_rehosting_fastdyn/FastDyn/boardrunner/boardrunner_sdk/model"

[Rehosting.milestones]
targets = ["HAL_ChibiOS::run"]
# ==============================================================================
#                              Memory Configuration
# ==============================================================================
[Memory]

[Memory.main]   # required: goes to -machine ... memory-backend=<id>
id = "ram0"
base_address = "0x20000000"
memory_size  = "512M"
memory_type  = "SRAM"
backend      = "file"          # file | ram | memfd
memory_file  = "../qemu/ws/my_m4_ram3"
share        = true
prealloc     = false

[[Memory.ram1]]   # optional banks: go to -global cortexm-soc.ram_backendN / ram_baseaddrN
id = "ram1"
index = 1
base_address = "0x30000000"
memory_size  = "512K"
memory_type  = "SRAM"
backend      = "file"
memory_file  = "../qemu/ws/my_m4_ram"
share        = true
prealloc     = false

# ==============================================================================
#                                CPU Configuration
# ==============================================================================
[Machine]
platform = "STM32F427"
# --- Debugging, Control, and Logging ---
qemu_path = "../qemu/build/qemu-system-arm"
enable_gdb = false
stop_on_start = false
launch_gdb = false
monitor_port = 5555
qmp_socket = "/tmp/qmp.sock"
log_file = "qemu.log"
log_options = "in_asm,op"
semihosting = true
semihosting_config = "enable=on,target=native"
coverage=true
finline='None'
print_command = true          #set to true if you want to print the final qemu on the terminal [Useful for debugging]
reset_memory_files = true     # clear file-backed RAM before QEMU starts to avoid stale SRAM across runs

[CPU]
[[CPU.cpu0]]
# --- Core Emulation & Plugin Settings ---
arch = "arm"
machine = "cortexm"
cpu = "cortex-m4"
plugin_library = "build/libfastdyn.so"
monitor_elf = "../qemu/ws/monitor.elf" # The VMM-like monitor that runs with the target
binary = "virtuals/physics/flight_controllers/courbet/bin/ardurover_v462"

init_nsvtor = "0x08004000"
twintrace = "None" #options are record, replay or None
hardware_trace = 'hardware_log/io.log'   #useful in cases like replay to generate the replay binary
introspect = false
# existing_config_path = "virtuals/physics/flight_controllers/courbet/rover462/unlabeled_conf"
symbol_file = "virtuals/physics/flight_controllers/courbet/bin/ardurover_v462"
optifuzz = false

# --- Embedded CPU Behavior Configurations ---
logger_content = """
# --- Plugin Logger Configuration ---
# level = DEBUG
# output = stderr
"""

# ==============================================================================
#                              Device Configuration
# ==============================================================================

# --- Model-Specific Configurations ---
# Define the global arguments for each type of plugin device model here.

[Device.Models.elder]
    # The libhw backend is a global argument for the elder model.

[Device.Models.passthrough]
    backend = "stlink"

[Device.Models.classic]
    # The classic model has no global arguments.

[Device.Models.twintrace]
    backend = "stlink"
    # The classic model has no global arguments.

[Device.Models.unhandled]
    # This model explicitly marks memory as unhandled.

# --- Peripheral Definitions ---
[Device.scb]
    ranges = [["0xe000ed00", "0xe000ed41"]]
    description = "SCB"
    read_priority = "elder"
    [[Device.scb.handlers]]
        model   = "elder"
        enabled = true
        scroll = "boardrunner/boardrunner_sdk/build/scb.so"

[Device.fpu]
    ranges = [["0xe000ef34", "0xe000ef41"]]
    description = "FPU"
    read_priority = "elder"
    [[Device.fpu.handlers]]
        model   = "elder"
        enabled = true
        scroll = "boardrunner/boardrunner_sdk/build/fpu.so"

[Device.fpu_cpacr]
    ranges = [["0xe000ed88", "0xe000ed8d"]]
    description = "FPU_CPACR"
    read_priority = "elder"
    [[Device.fpu_cpacr.handlers]]
        model   = "elder"
        enabled = true
        scroll = "boardrunner/boardrunner_sdk/build/fpu_cpacr.so"

[Device.rcc]
    ranges = [["0x40023800", "0x40023c00"]]
    description = "RCC"
    read_priority = "elder"
    [[Device.rcc.handlers]]
        model   = "elder"
        enabled = true
        scroll = "boardrunner/boardrunner_sdk/build/rcc.so"

[Device.gpioa]
    ranges = [["0x40020000", "0x40020400"]]
    description = "GPIOA"
    read_priority = "elder"
    [[Device.gpioa.handlers]]
        model   = "elder"
        enabled = true
        scroll = "boardrunner/boardrunner_sdk/build/gpioa.so"

[Device.gpiob]
    ranges = [["0x40020400", "0x40020800"]]
    description = "GPIOB"
    read_priority = "elder"
    [[Device.gpiob.handlers]]
        model   = "elder"
        enabled = true
        scroll = "boardrunner/boardrunner_sdk/build/gpiob.so"

[Device.gpioc]
    ranges = [["0x40020800", "0x40020c00"]]
    description = "GPIOC"
    read_priority = "elder"
    [[Device.gpioc.handlers]]
        model   = "elder"
        enabled = true
        scroll = "boardrunner/boardrunner_sdk/build/gpioc.so"

[Device.gpiod]
    ranges = [["0x40020c00", "0x40021000"]]
    description = "GPIOD"
    read_priority = "elder"
    [[Device.gpiod.handlers]]
        model   = "elder"
        enabled = true
        scroll = "boardrunner/boardrunner_sdk/build/gpiod.so"

[Device.gpioe]
    ranges = [["0x40021000", "0x40021400"]]
    description = "GPIOE"
    read_priority = "elder"
    [[Device.gpioe.handlers]]
        model   = "elder"
        enabled = true
        scroll = "boardrunner/boardrunner_sdk/build/gpioe.so"

[Device.gpiof]
    ranges = [["0x40021400", "0x40021800"]]
    description = "GPIOF"
    read_priority = "elder"
    [[Device.gpiof.handlers]]
        model   = "elder"
        enabled = true
        scroll = "boardrunner/boardrunner_sdk/build/gpiof.so"

[Device.gpiog]
    ranges = [["0x40021800", "0x40021c00"]]
    description = "GPIOG"
    read_priority = "elder"
    [[Device.gpiog.handlers]]
        model   = "elder"
        enabled = true
        scroll = "boardrunner/boardrunner_sdk/build/gpiog.so"

[Device.gpioh]
    ranges = [["0x40021c00", "0x40022000"]]
    description = "GPIOH"
    read_priority = "elder"
    [[Device.gpioh.handlers]]
        model   = "elder"
        enabled = true
        scroll = "boardrunner/boardrunner_sdk/build/gpioh.so"

[Device.gpioi]
    ranges = [["0x40022000", "0x40022400"]]
    description = "GPIOI"
    read_priority = "elder"
    [[Device.gpioi.handlers]]
        model   = "elder"
        enabled = true
        scroll = "boardrunner/boardrunner_sdk/build/gpioi.so"

[Device.pwr]
    ranges = [["0x40007000", "0x40007400"]]
    description = "PWR"
    read_priority = "elder"
    [[Device.pwr.handlers]]
        model   = "elder"
        enabled = true
        scroll = "boardrunner/boardrunner_sdk/build/pwr.so"
