use scirs2_optimize::global::{ 
    BayesianOptimizationOptions,
    BayesianOptimizer,
    Space
};
use scirs2_optimize::prelude::Parameter;
use scirs2_core::ndarray::Array1;

// Want the optimizer to converge towards this value
const OPT_TARGET: f64 = 0.25;
const INITIAL_POINTS: usize = 100;
const LOWER_BOUND: f64 = -1.0;
const UPPER_BOUND: f64 = 1.0;

fn my_ask_and_tell(bo: &mut BayesianOptimizer, iterations: usize) {
    for i in 0..iterations {
        let input = bo.ask();

        /*
        During the optimization phase, the optimizer may suggest input values
        outside of the defined search space. We need to clamp/round every numeric 
        input generated by the optimizer.
        */
        // let real_value = input[0].clamp(LOWER_BOUND, UPPER_BOUND);

        let categorical_value = input[0];

        // I probably won't use int parameters since the optimizer doesn't even generate discrete ints lol
        // Integer ardurover params can be handled with categorical space
        // let int_value = input[1].round() as i64;


        // let robustness = f64::abs(OPT_TARGET - real_value);
        let robustness = 0.0;
        println!("ITERATION {i}:");
        // println!("\tGot from optimizer: {real_value}, {categorical_value}");
        println!("\tGot from optimizer: {categorical_value}");
        println!("\tSimulated Robustness: {robustness}");
        // let my_input = Array1::<f64>::from_vec(vec![-1.1]);
        // bo.tell(Array1::from_vec(vec![real_value, categorical_value]), robustness);
        bo.tell(input, robustness);
        // bo.tell(my_input, robustness); 
    }
}

fn main() {
    
    println!("EXPERIMENT DETAILS:");
    println!("\tTarget input: {OPT_TARGET}");
    println!("\tSearch bounds: ({LOWER_BOUND}, {UPPER_BOUND})");
    println!("\tNumber of points to explore before optimization: {INITIAL_POINTS}");

    // Define search space
    let mut space = Space::new(); //.add("Burger", Parameter::Real(LOWER_BOUND, UPPER_BOUND));
    // space = space.add("real_param", Parameter::Real(LOWER_BOUND, UPPER_BOUND));
    // space = space.add("int_param", Parameter::Integer(-10, 10));
    space = space.add("categorical_param", Parameter::Categorical(vec!["A".to_string(), "B".to_string(), "C".to_string()]));

    // Create optimizer options with more evaluations
    let mut options = BayesianOptimizationOptions::default();
    options.n_initial_points = INITIAL_POINTS;

    // Create optimizer
    let mut bo = BayesianOptimizer::new(space, Some(options));

    println!("---------------------------------------------------");
    println!("TRAINING OPTIMIZER WITH {INITIAL_POINTS} INITIAL POINTS...");
    my_ask_and_tell(&mut bo, INITIAL_POINTS);
    println!("---------------------------------------------------");
    println!("What did the optimizer learn??");
    println!("---------------------------------------------------");
    my_ask_and_tell(&mut bo, 20);

} 