# ==============================================================================
#                              Memory Configuration
# ==============================================================================
[Memory]

[Memory.main]   # required: goes to -machine ... memory-backend=<id>
id = "ram0"
base_address = "0x20000000"
memory_size  = "512M"
memory_type  = "SRAM"
backend      = "file"          # file | ram | memfd
memory_file  = "/dev/shm/my_m4_ram3"
share        = true
prealloc     = false

[[Memory.ram1]]   # optional banks: go to -global cortexm-soc.ram_backendN / ram_baseaddrN
id = "ram1"
index = 1
base_address = "0x30000000"
memory_size  = "512K"
memory_type  = "SRAM"
backend      = "file"
memory_file  = "/dev/shm/my_m4_ram"
share        = true
prealloc     = false

# ==============================================================================
#                                CPU Configuration
# ==============================================================================
[Machine]
platform = "STM32F103xx"
# --- Debugging, Control, and Logging ---
qemu_path = "qemu-system-arm"
enable_gdb = true
stop_on_start = true
launch_gdb = false
monitor_port = 5555
qmp_socket = "/tmp/qmp.sock"
log_file = "qemu.log"
log_options = "in_asm,op"
semihosting = true
semihosting_config = "enable=on,target=native"
coverage=true
finline='None'
bbl_coverage=true             #set to true or false to calculate bbl coverage

[CPU]
[[CPU.cpu0]]
# --- Core Emulation & Plugin Settings ---
arch = "arm"
machine = "cortexm"
cpu = "cortex-m3"
plugin_library = "build/libfastdyn.so"
monitor_elf = "../ws/monitor.elf" # The VMM-like monitor that runs with the target
binary = "boardrunner/boardrunner_examples/examples/Nucleo-F103RB/SPI/firmwares/STM32F103RB_Nucleo.elf"
init_nsvtor = "0x08000000"
map_file = "courbet/rover_v422_map.txt"
twintrace = "None" #options are record, replay or None
hardware_trace = 'hardware_log/io.log'   #useful in cases like replay to generate the replay binary

# --- Embedded CPU Behavior Configurations ---
logger_content = """
# --- Plugin Logger Configuration ---
# level = DEBUG
# output = stderr
"""

# assert at hard fault
# [[CPU.cpu0.virtuals]]
# at = "0x08001116"
# instruction = "assert"
# args = ["*0x0"]

# ==============================================================================
#                              Device Configuration
# ==============================================================================

# --- Model-Specific Configurations ---
# Define the global arguments for each type of plugin device model here.

[Device.Models.elder]
    # The libhw backend is a global argument for the elder model.

[Device.Models.passthrough]
    backend = "stlink"

[Device.Models.classic]
    # The classic model has no global arguments.

[Device.Models.twintrace]
    backend = "stlink"
    # The classic model has no global arguments.

[Device.Models.unhandled]
    # This model explicitly marks memory as unhandled.

# --- Peripheral Definitions ---
# Each peripheral gets its own sub-table. If it uses the elder model,
# its specific scroll configuration is defined directly within it.
    [Device.spi]
        ranges = [["0x40003800", "0x40003BFF"], ["0x40010C00", "0x40010FFF"]] #handles spi2 peripheral, cs pin for gpio
        irq = ['3','15']
        description = "spi Peripheral"
        read_priority = "elder"  #only the read from elder model is considered.
        # The configuration for this specific device when handled by the elder model.
        [[Device.spi.handlers]]
            # This device is now handled by the elder model, directly linking it
            # to the 'scroll_config' defined above.
            model   = "elder"
            enabled = true
            scroll = "boardrunner/boardrunner_sdk/build/spi_model.so"

        [[Device.spi.slaves]]
            model = ["elder"]       # attach this device to elder model only
            device = "bme280"
            cs_id = 0               # (Connect this slave to CS Line 0)
            device_scroll = "boardrunner/boardrunner_sdk/build/spi_slave.so"

        [[Device.spi.handlers]]
            model   = "classic"
            enabled = false

        [[Device.spi.handlers]]
            # This device is now handled by the elder model, directly linking it
            # to the 'scroll_config' defined above.
            model   = "passthrough"
            enabled = false

        [[Device.spi.handlers]]
            model   = "twintrace"
            enabled = false

    [Device.remaining_space]
        ranges = [
        ["0x40000000", "0x400037FF"],   # before SPI2
        ["0x40003C00", "0x40010BFF"],   # after SPI2 up to before GPIOB
        ["0x40011000", "0xE0000000"],   # after GPIOB onward (GPIOC starts at 0x40011000)
        ["0xE0000000", "0xEFFFFFFF"]
        ]
        irq = ['3','15']
        description = "Memory regions that will handled by passthrough and are not of interest for the modeling."

        [[Device.remaining_space.handlers]]
            model = "classic"
            enabled = false

        [[Device.remaining_space.handlers]]
            model = "passthrough"
            enabled = true

        [[Device.remaining_space.handlers]]
            model = "twintrace"
            enabled = false