
# ==============================================================================
# Machine
# ==============================================================================
[Machine]
platform = "STM32F429"

qemu_path = "qemu-system-arm"

monitor_port = 5554
qmp_socket   = "/tmp/qmp.sock"

enable_gdb    = false
stop_on_start = false
launch_gdb    = false

semihosting        = true
semihosting_config = "enable=on,target=native"

coverage = true
finline  = ""

# ==============================================================================
# Memory
# ==============================================================================
[Memory]

  [Memory.main]
  id           = "ram0"
  base_address = "0x20000000"
  memory_size  = "512M"
  memory_type  = "SRAM"

  backend     = "file"
  memory_file = "/dev/shm/my_m4_ram3"

  share    = true
  prealloc = false

  [[Memory.ram1]]
  id           = "ram1"
  index        = 1
  base_address = "0x30000000"
  memory_size  = "512K"
  memory_type  = "SRAM"

  backend     = "file"
  memory_file = "/dev/shm/my_m4_ram"

  share    = true
  prealloc = false

# ==============================================================================
# CPUs
# ==============================================================================
[CPU]

  [[CPU.cpu0]]
  arch    = "arm"
  machine = "cortexm"
  cpu     = "cortex-m4"

  binary     = "boardrunner/boardrunner_examples/examples/STM32F429i-disc1/pwm/firmwares/pwm.axf"
  init_nsvtor = "0x08000000"

  plugin_library  = "build/libfastdyn.so"
  monitor_elf     = "../ws/monitor.elf"

  log_file    = "qemu.log"
  log_options = "in_asm,op"

  twintrace = "None"
  hardware_trace = 'hardware_log/io.log'

  logger_content = """
  # --- Plugin Logger Configuration ---
  # level  = DEBUG
  # output = stderr
  """

# ==============================================================================
# Device Configuration
# ==============================================================================

[Device.Models.elder]

[Device.Models.passthrough]
    backend = "stlink"

[Device.Models.classic]

[Device.Models.twintrace]
    backend = "stlink"

[Device.Models.unhandled]

# --- TIM3 (General-purpose timer, APB1) ---
[Device.tim3]
    ranges = [["0x40000400", "0x400007FF"]]
    description = "TIM3 general-purpose timer in PWM mode on Channel 1 (PA6)."
    read_priority = "elder"

    [[Device.tim3.handlers]]
        model   = "elder"
        enabled = true
        scroll  = "boardrunner/boardrunner_sdk/build/model.so"

    [[Device.tim3.handlers]]
        model   = "passthrough"
        enabled = false


# --- Everything else (passthrough), with a hole for TIM3 ---
[Device.unhandled_space]
    ranges = [
      ["0x40000000", "0x400003FF"],   # before TIM3
      ["0x40000800", "0xEFFFFFFF"]    # after TIM3
    ]
    description = "All other MMIO space (passthrough), excluding TIM3 window."

    [[Device.unhandled_space.handlers]]
        model = "passthrough"
        enabled = true
